<body>

<link rel="stylesheet" href="style.css">


<table width=100% bgcolor=#bce954 cellpadding=10>

<!--
<td align=left><img src="logo-st-andrews-stacked-600-mono.gif"></td>
-->
<td>
<h2>LMS/EPSRC Short Instructional Course</h2>
<h1>Computational Group Theory</h1>
<h1>St Andrews 2013</h1>
</td>

<td align=right>
<img src="NorthStreetsmall300.jpg"><br>
<font size="-2">Image &#169 The University of St Andrews</font>
</td>

</table>