<table border=0 cellspacing=0 cellpadding=10 width=100% height=100%>
<tr><td width=18% valign=top>
<ul>
<b>
<li>
<a href="index.shtml">Course Home</a>
<br>
<br>
<li>
<a href="programme.shtml">Programme</a>
<br>
<br>
<li>
<a href="timetable.shtml">Academic and Social Timetable</a>
<br>
<br>
<li>
<a href="participants.shtml">Information for Participants after Arrival</a>
<br>
<br>
<li>
<a href="lectures.shtml">The Lectures and Worksheets</a>
<br>
<br>
<li>
<a href="registration.shtml">Registration (closed) and Payments</a>
<br>
<br>
<li>
<a href="accommodation.shtml">Accommodation and Food</a>
<br>
<br>
<li>
<a href="whattodohere.shtml">Things to do in St Andrews</a>
<br>
<br>
<li>
<a href="travel.shtml">Travel and Arrival</a>
<br>
<br>
<li>
<a href="contact.shtml">Contact us</a>
</ul>
<br>
</b>
</td>


<td align=left valign=top>

<!--
<img src="NorthStreetsmall.jpg">
<p>
<sub>Image copyright The University of St Andrews</sub>
</p>
-->


<!--
<table border=0 cellpadding=10 cellspacing=0 width=100%><tr>
-->